Add a link to the embed view of the metric in the Slack notifications
corradio/polynomial pull request #185
Opened 2024-07-03 07:56 UTC by madsnedergaard

To make it easier to follow-up and see the live graph with recent changes, I think it would be nice to link to it from the Slack notifications.

Since a metric can belong to multiple dashboards, I think the easiest solution is to just use the `/embed` link as a start :)

2024-07-05 01:46 UTC, corradio requested changes

2024-07-05 01:46 UTC, corradio commented on mainapp/tasks/__init__.py
> +            link = f"https://polynomial.so/metrics/{metric_id}/embed"
Hi @madsnedergaard,
Thanks for the contribution!
I added a new `metric-details` route [here](https://github.com/corradio/polynomial/commit/ba1997306ad6f18bbc8fab20c18e2d34cf6bac40#diff-742b0a5d9e820d2640675ab798fc9eec0ffdb9079cf908e84ee519c105614d9eR625), which is the same as `/embed` but with proper access rights and with header/footer for the UI.

I also suggest constructing the url from the named routes:
```suggestion
            link = f"{BASE_URL}{reverse('metric-details', args=[metric_id])}"
```

using:
```python
from config.settings import CSRF_TRUSTED_ORIGINS

BASE_URL = CSRF_TRUSTED_ORIGINS[0]
```

The `BASE_URL` is a bit hacky but at least it's consistent with [this](https://github.com/corradio/polynomial/blob/master/mainapp/tasks/error_handling.py#L45).

2024-08-26 05:06 UTC, corradio commented on mainapp/tasks/__init__.py
> +            link = f"https://polynomial.so/metrics/{metric_id}/embed"
Hi @madsnedergaard , let me know if you need anything from me!

2024-10-01 07:31 UTC, madsnedergaard commented on mainapp/tasks/__init__.py
> +            link = f"https://polynomial.so/metrics/{metric_id}/embed"
Sorry it took a while, should be fixed now - I used the `reverse()` method used elsewhere, although I'm not 100% certain how that actually works ¯\\\_(ツ)\_/¯

2024-10-01 07:53 UTC, corradio approved these changes

2024-10-01 07:53 UTC, corradio commented on Makefile
> +	DJANGO_SUPERUSER_USERNAME=john \
john is a better name for an admin than `admin` 👍

2024-10-01 07:53 UTC, corradio commented on mainapp/tasks/__init__.py
> +            link = f"https://polynomial.so/metrics/{metric_id}/embed"
FYI it gets the URL by key, as defined in urls.py here:
https://github.com/corradio/polynomial/blob/master/mainapp/urls.py#L34

2024-10-01 07:59 UTC, merged